### ISSUE TITLE
Update version of Go library

### ISSUE THREAD

**Issue by hwittenborn** [trevyn/librclone#3]
Hi! I'm starting to look into using this for a program I'm making, and I noticed the Go version of librclone that's being used appears to be out of date (1.56 from what I'm seeing)?

Could the library version be updated? I'm probably gonna end up using this library regardless, but just knowing it's up to date for things like bug and security fixes would just be a good peace of mind.

**Comment by trevyn** [comment]
Updated rclone to latest v1.60.1 and published on crates.io as 0.2.0.

Let me know how it goes!

**Comment by hwittenborn** [comment]
Hey! I just got to moving my application over to the new version, and it's all continuing to work fine still. With how it's going for my application in general it's just darn amazing - I was gonna be implementing some stuff manually and now it's a heck of a lot easier since I just let rclone deal with all the messy parts now. I can't say too much on what my application is yet though, I'm trying to make sure it really has a shot going for it once it's complete ;).

Anyway, thanks for getting this updated, I really appreciate it! :)
