### ISSUE TITLE
Update to latest librclone version

### ISSUE THREAD

**Issue by hwittenborn** [trevyn/librclone#6]
Hey again! librclone just had another release and there's some stuff in it I was needing for my application - I've been using a local copy as of current but I'd like to go back to using a crates.io release if I could.

On a side note, would it be possible to version the `librclone-sys` crate under the same versions as librclone itself, and then have `librclone` have any version required (or maybe make that match versions too)? I don't know what the current logic for the versioning is, but I feel like following upstream versions - at least for the `-sys` crate - would be cleaner.

**Comment by trevyn** [comment]
You're fast!

Versioning is a little tricky; the ultimate intent is to follow Rust semver: Doing `cargo update` and pulling in semver-minor or patch changes should *never* break your code.

With `librclone`, there's the extra complication of changes to the underlying RPC commands; I'm not sure if the rclone project has any stability guarantees on that API.

What I have seen some projects do is use the semver "build metadata" field to informationally show the version of the underlying library, e.g.:

[`zstd-sys = "2.0.4+zstd.1.5.2"`](https://crates.io/crates/zstd-sys/versions)
[`libgit2-sys = "0.14.0+1.5.0"`](https://crates.io/crates/libgit2-sys/versions)
[`curl-sys = "0.4.59+curl-7.86.0"`](https://crates.io/crates/curl-sys/versions)

Would this be useful to you?

**Comment by hwittenborn** [comment]
Yeah, I've definitely been on the lookout for their next release to come out lol.

> What I have seen some projects do is use the semver "build metadata" field to informationally show the version of the underlying library

Considering that big projects like the libgit2 bindings are doing it I think that's a good approach, just being able to track the version of librclone that's being used via the crate version itself would be nice for me - obviously you can't do that with the wrapper because you never know when something might need changed in the wrapper itself, but for the direct bindings I think that'd be nice.

**Comment by trevyn** [comment]
Published
`librclone 0.3.0`
and
`librclone-sys 0.3.0+rclone-v1.61.0`

**Comment by hwittenborn** [comment]
Thanks a ton, appreciate it again!
