### ISSUE TITLE
Support rclone v1.63.0

### ISSUE THREAD

**Issue by xenago** [trevyn/librclone#9]
A new rclone release is out as of [2023-06-30](https://rclone.org/changelog/#v1-63-0-2023-06-30) 🎉

**Comment by trevyn** [comment]
Cool! Looks like there’s a regression and a 1.63.1 in the works: https://github.com/rclone/rclone/issues/7114

I’ll bump once that gets released.

**Comment by trevyn** [comment]
Published
`librclone 0.5.0`
and
`librclone-sys 0.5.0+rclone-v1.63.1`
